COMMON_FLAGS="-O2 -pipe -flto=auto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LC_MESSAGES=C.UTF-8
USE="-gdk-pixbuf -sysprof fontconfig webp minizip harfbuzz"
